config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }, path: '/', path_names: {
      sign_in: 'login', sign_out: 'logout',
      password: 'secret', confirmation: 'verification',
      registration: 'register', edit: 'edit/profile'
  }
  authenticate :user do
    resources :bills do
      resources :bill_apportionments
    end  
    resources :bill_types do
      resources :bill_splitings
    end
    resources :houses, only: [:new, :create]
  end

  authenticated :user do
    root 'bill_types#index', as: :authenticated_root
  end
  root to: "home#index"
  #get 'bill_types/:id/split', action: :split, controller: 'bill_types', as: :bill_types_split
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bill_spliting.rb
class BillSpliting < ApplicationRecord
    belongs_to :dweller
    belongs_to :bill_type
end

app/controllers/bill_splitings_controller.rb
class BillSplitingsController < ApplicationController
  before_action :set_bill_splitings
  before_action :set_bill_spliting, only: [:show, :edit, :update, :destroy]
  before_action :require_living

  # GET bill_types/1/bill_splitings
  def index
    @bill_splitings = @bill_type.bill_splitings
  end

  # GET bill_types/1/bill_splitings/1
  def show
  end

  # GET bill_types/1/bill_splitings/new
  def new
    @dwellers = Dweller.where("house_id = ?", current_user.dweller.house.id)
    
    @bill_spliting = @bill_type.bill_splitings.build
  end

  # GET bill_types/1/bill_splitings/1/edit
  def edit
  end

  # POST bill_types/1/bill_splitings
  def create
      @bill_spliting = BillSpliting::Create.new(@bill_type, bill_spliting_params).call()
      redirect_to bill_type_bill_splitings_path, notice: 'Bill spliting was successfully created.'
    rescue => e
      flash.now[:error] = e.message
      @bill_spliting = @bill_type.bill_splitings.build(bill_spliting_params)
      #TODO: just dwellers from the right house
      @dwellers = Dweller.all
      render :new
  end

  # PUT bill_types/1/bill_splitings/1
  def update
    if @bill_spliting.update_attributes(bill_spliting_params)
      redirect_to([@bill_spliting.bill_type, @bill_spliting], notice: 'Bill spliting was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE bill_types/1/bill_splitings/1
  def destroy
    @bill_spliting.destroy

    redirect_to bill_type_bill_splitings_url(@bill_type)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill_splitings
      @bill_type = BillType.find(params[:bill_type_id])
    end

    def set_bill_spliting
      @bill_spliting = @bill_type.bill_splitings.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def bill_spliting_params
      params.require(:bill_spliting).permit(:value, :dweller_id)
    end
end

app/helpers/bill_splitings_helper.rb
module BillSplitingsHelper
end

app/views/bill_splitings/_form.html.erb
<%= form_for([@bill_spliting.bill_type, @bill_spliting]) do |f| %>
  <% if @bill_spliting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill_spliting.errors.count, "error") %> prohibited this bill_spliting from being saved:</h2>

      <ul>
      <% @bill_spliting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :dweller %>
    <%= f.collection_select :dweller_id, @dwellers, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bill_splitings/edit.html.erb
<h1>Editing bill_spliting</h1>

<%= render 'form' %>

<%= link_to 'Show', [@bill_spliting.bill_type, @bill_spliting] %> |
<%= link_to 'Back', bill_type_bill_splitings_path(@bill_spliting.bill_type) %>

app/views/bill_splitings/index.html.erb
<h1>Listing bill_splitings</h1>

<table>
  <tr>
    <th>Value</th>
    <th>total: <%= @bill_type.total_value %></th>
    <th>real: <%= @bill_type.value %></th>
  </tr>

<% @bill_splitings.each do |bill_spliting| %>
  <tr>
    <td><%= bill_spliting.value %></td>
    <td><%= link_to 'Show', [bill_spliting.bill_type, bill_spliting], class: "btn btn-primary float-right" %></td>
    <td><%= link_to 'Edit', edit_bill_type_bill_spliting_path(bill_spliting.bill_type, bill_spliting),  class: "btn btn-primary float-right" %></td>
    <td><%= link_to 'Destroy', [bill_spliting.bill_type, bill_spliting], :confirm => 'Are you sure?', :method => :delete,  class: "btn btn-danger float-right" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bill spliting', new_bill_type_bill_spliting_path(params[:bill_type_id]), class: "btn btn-primary" %>
<div class="col-md-11 text-center">
  <%= link_to 'Back', bill_types_path, class: "btn btn-warning text-center" %>
</div>

app/views/bill_splitings/new.html.erb
<h1>New bill_spliting</h1>

<%= render 'form' %>

<%= link_to 'Back to bill spliting', bill_type_bill_splitings_path(@bill_spliting.bill_type) %>
<%= link_to 'Back to bill type', bill_type_path(@bill_spliting.bill_type) %>

app/views/bill_splitings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Value:</b>
  <%= @bill_spliting.value %>
</p>


<%= link_to 'Edit', edit_bill_type_bill_spliting_path(@bill_spliting.bill_type, @bill_spliting) %> |
<%= link_to 'Back', bill_type_bill_splitings_path(@bill_spliting.bill_type) %>