config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }, path: '/', path_names: {
      sign_in: 'login', sign_out: 'logout',
      password: 'secret', confirmation: 'verification',
      registration: 'register', edit: 'edit/profile'
  }
  authenticate :user do
    resources :bills do
      resources :bill_apportionments
    end  
    resources :bill_types do
      resources :bill_splitings
    end
    resources :houses, only: [:new, :create]
  end

  authenticated :user do
    root 'bill_types#index', as: :authenticated_root
  end
  root to: "home#index"
  #get 'bill_types/:id/split', action: :split, controller: 'bill_types', as: :bill_types_split
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bill.rb
class Bill < ApplicationRecord
  has_many :bill_apportionments, dependent: :destroy, inverse_of: :bill
  belongs_to :bill_month
  belongs_to :bill_type

  accepts_nested_attributes_for :bill_apportionments, reject_if: :all_blank, allow_destroy: true
end

app/models/bill_type.rb
class BillType < ApplicationRecord
  belongs_to :responsible, foreign_key: 'dweller_id', class_name: 'Dweller'
  belongs_to :house
  has_many :bill_splitings, dependent: :destroy, inverse_of: :bill_type
  has_many :dwellers, through: :bill_splitings
  has_many :bills, dependent: :destroy

  accepts_nested_attributes_for :bill_splitings, reject_if: :all_blank, allow_destroy: true

  def total_value
      BillSpliting.where(bill_type: self).sum(:value)
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]
  before_action :require_living

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    house_id = current_user.dweller.house.id
    @bill = Bill.new
    @bill_apportionments = @bill.bill_apportionments.build
    @dwellers = Dweller.where("house_id = ?", house_id)
    @bill_type = BillType.where("house_id = ?", house_id)
  end

  # GET /bills/1/edit
  def edit
    @bill_apportionments = @bill.bill_apportionments.build
    @dwellers = Dweller.where("house_id = ?", current_user.dweller.house.id)
  end

  # POST /bills
  # POST /bills.json
  def create
    Bill::Create.new(new_bill_params).call
    redirect_to bills_path, notice: 'Bill was successfully created.'
    rescue Exception => e
      flash.now[:error] = e.message
      @bill = Bill.new(bill_params)
      render :new
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:paid_value, :month_value, :paid_date, :maturity_date, :bill_month_id, :bill_type_id, bill_apportionments_attributes: [:id, :value, :dweller_id, :_destroy])
    end

    #to convert dates to DateTime objects
    def new_bill_params
      new_params = bill_params
      
      for x in (1..5) do
        #eval('new_params[:paid_date] = params[:bill]["paid_date(#{x}i)"].to_i ')
        eval('new_params.delete("paid_date(#{x}i)")')
      end

      for x in (1..5) do
        #eval('new_params[:maturity_date] = params[:bill]["maturity_date(#{x}i)"].to_i ')
        eval('new_params.delete("maturity_date(#{x}i)")')
      end
      
      new_params[:paid_date] = DateTime.new(params[:bill]["paid_date(1i)"].to_i, 
                                            params[:bill]["paid_date(2i)"].to_i, 
                                            params[:bill]["paid_date(3i)"].to_i, 
                                            params[:bill]["paid_date(4i)"].to_i, 
                                            params[:bill]["paid_date(5i)"].to_i)

      new_params[:maturity_date] = DateTime.new(params[:bill]["maturity_date(1i)"].to_i, 
                                                params[:bill]["maturity_date(2i)"].to_i, 
                                                params[:bill]["maturity_date(3i)"].to_i, 
                                                params[:bill]["maturity_date(4i)"].to_i, 
                                                params[:bill]["maturity_date(5i)"].to_i)

      new_params
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_bill_apportionment_fields.html.erb
<div class="nested-fields square">
  <%= f.input :value %>
  <%= f.label :dweller %>
  <%= f.collection_select :dweller_id, @dwellers, :id, :name %>
  <%= link_to_remove_association "remover rateio", f, class: "btn btn-danger" %>
</div>
<br>

app/views/bills/_form.html.erb
<%= simple_form_for(@bill) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :bill_type, collection: @bill_type %>
    <%= f.input :paid_value %>   
    <%#= f.input :month_value %>
    <%= f.input :paid_date, as: :date, html5: true %>
    <%= f.input :maturity_date, as: :date, html5: true %>
    <%= f.association :bill_month, label_method: :status, as: :radio_buttons %> 
  </div>

   <div id="bill_apportionments">
    <%= f.simple_fields_for :bill_apportionments do |bill_apportionment| %>
      <%= render 'bill_apportionment_fields', f: bill_apportionment %>
    <% end %>
  </div>

  <div class="links">
    <%= link_to_add_association 'novo rateio', f, :bill_apportionments, class: "btn btn-primary float-right" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form', bill: @bill %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lançamento de contas</h1>

<table>
  <thead>
    <tr>
      <th>Valor pago</th>
      <th>Valor do mês</th>
      <th>Data paga</th>
      <th>Data do vencimento</th>
      <th>Status</th>
      <th>Conta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.paid_value %></td>
        <td><%= bill.month_value %></td>
        <td><%= bill.paid_date.strftime('%a %d %b %Y') %></td>
        <td><%= bill.maturity_date.strftime('%a %d %b %Y')  %></td>
        <td><%= bill.bill_month.status %></td>
        <td><%= bill.bill_type.name %></td>
        <td><%= link_to 'Abrir', bill, class: "btn btn-primary" %></td>
        <td><%= link_to 'Editar', edit_bill_path(bill), class: "btn btn-primary float-right" %></td>
        <td><%= link_to 'Apagar', bill, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        <td><%= link_to 'Rateio', bill_bill_apportionments_path(bill), class: "btn btn-warning" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo lançamento de conta', new_bill_path, class: "btn btn-primary" %>

app/views/bills/new.html.erb
<h1>Novo lançamento de conta</h1>

<%= render 'form', bill: @bill %>

<div class="col-md-11 text-center">
  <%= link_to 'Voltar', bills_path, class: "btn btn-warning text-center" %>
</div>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Paid value:</strong>
  <%= @bill.paid_value %>
</p>

<p>
  <strong>Month value:</strong>
  <%= @bill.month_value %>
</p>

<p>
  <strong>Paid date:</strong>
  <%= @bill.paid_date %>
</p>

<p>
  <strong>Maturity date:</strong>
  <%= @bill.maturity_date %>
</p>

<p>
  <strong>Bill month:</strong>
  <%= @bill.bill_month %>
</p>

<p>
  <strong>Bill type:</strong>
  <%= @bill.bill_type %>
</p>

<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>