config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }, path: '/', path_names: {
      sign_in: 'login', sign_out: 'logout',
      password: 'secret', confirmation: 'verification',
      registration: 'register', edit: 'edit/profile'
  }
  authenticate :user do
    resources :bills do
      resources :bill_apportionments
    end  
    resources :bill_types do
      resources :bill_splitings
    end
    resources :houses, only: [:new, :create]
  end

  authenticated :user do
    root 'bill_types#index', as: :authenticated_root
  end
  root to: "home#index"
  #get 'bill_types/:id/split', action: :split, controller: 'bill_types', as: :bill_types_split
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/bill_types_controller.rb
class BillTypesController < ApplicationController
  before_action :set_bill_type, only: [:show, :edit, :update, :destroy, :split]
  before_action :require_living

  # GET /bill_types
  # GET /bill_types.json
  def index
    #FIX: IF USER DOESNT HAVE A HOUSE, IT GIVES AN ERROR
    @bill_types = BillType.where('house_id = ?', current_user.dweller.house.id)
  end

  # GET /bill_types/1
  # GET /bill_types/1.json
  def show
  end

  # GET /bill_types/new
  def new
    @bill_type = BillType.new
    @bill_splitings = @bill_type.bill_splitings.build
    @dwellers = Dweller.where("house_id = ?", current_user.dweller.house.id)
  end

  # GET /bill_types/1/edit
  def edit
    @bill_splitings = @bill_type.bill_splitings
    @dwellers = Dweller.where("house_id = ?", current_user.dweller.house.id)
  end

  # POST /bill_types
  # POST /bill_types.json
  def create
    # REFACTOR BECAUSE IT CONSULTS A LOT OF DB
    responsible = current_user.dweller  
    params = bill_type_params   
    params[:house_id] = current_user.dweller.house.id
    
    BillType::Create.new(responsible, params).call()
    redirect_to bill_types_path, notice: 'Bill type was successfully created.'
    rescue Exception => e
      flash.now[:error] = e.message
      @bill_type = BillType.new(bill_type_params)
      render :new
  end

  # PATCH/PUT /bill_types/1
  # PATCH/PUT /bill_types/1.json
  def update
    respond_to do |format|
      if @bill_type.update(bill_type_params)
        format.html { redirect_to @bill_type, notice: 'Bill type was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill_type }
      else
        format.html { render :edit }
        format.json { render json: @bill_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bill_types/1
  # DELETE /bill_types/1.json
  def destroy
    @bill_type.destroy
    respond_to do |format|
      format.html { redirect_to bill_types_url, notice: 'Bill type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill_type
      @bill_type = BillType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_type_params
      params.require(:bill_type).permit(:name, :description, :maturity, :value, bill_splitings_attributes: [:id, :value, :dweller_id, :_destroy])
    end
end

app/helpers/bill_types_helper.rb
module BillTypesHelper
end

app/views/bill_types/_bill_spliting_fields.html.erb
<div class="nested-fields square">
  <%= f.label :value %>
  <input type="radio" name="valor" value="ativado" id="radio_value"> Ativar<br>
  <%= f.input :value, input_html: {id: "bill_spliting_value"}, label: false %>
  <%= f.label :percentage_value %>
  <input type="radio" name="valor" value="ativado" id="radio_percentage_value"> Ativar<br>
  <%= f.input :percentage_value, input_html: {id: "bill_spliting_percentage_value"}, label: false %>
  <%= f.label :dweller %>
  <%= f.collection_select :dweller_id, @dwellers, :id, :name %>
  <%= link_to_remove_association "remover divisão de conta", f, class: "btn btn-danger" %>
</div>
<br>

app/views/bill_types/_form.html.erb
<%= simple_form_for @bill_type do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <%= f.input :name %>
  <%= f.input :description %>
  <%#= f.input :maturity, as: :date %>
  <%= f.input :value, as: :decimal %>

  <h3>Divisão de contas</h3>

  <div id="bill_splitings">
    <%= f.simple_fields_for :bill_splitings do |bill_spliting| %>
      <%= render 'bill_spliting_fields', f: bill_spliting %>
    <% end %>
  </div>
  
  <div class="links">
    <%= link_to_add_association 'adicionar nova divisão', f, :bill_splitings, class: "btn btn-primary float-right" %>
  </div>

  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/bill_types/edit.html.erb
<h1>Editar conta</h1>

<%= render 'form', bill_type: @bill_type %>

<%= link_to 'Show', @bill_type %> |
<%= link_to 'Back', bill_types_path %> |
<%= link_to 'Split', bill_type_bill_splitings_path(@bill_type) %>

app/views/bill_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contas cadastradas</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bill_types.each do |bill_type| %>
      <tr>
        <td><%= link_to bill_type.name , bill_type, class: "btn" %></td>
        <td><%= link_to 'Editar', edit_bill_type_path(bill_type), class: "btn btn-primary float-right" %></td>
        <td><%= link_to 'Apagar', bill_type, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        <td><%= link_to 'Dividir', bill_type_bill_splitings_path(bill_type), class: "btn btn-warning" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Cadastrar nova conta', new_bill_type_path, class: "btn btn-primary" %>

app/views/bill_types/new.html.erb
<h1>Cadastrar nova conta</h1>

<%= render 'form' %>
<br>
<div class="col-md-11 text-center">
  <%= link_to 'Voltar', bill_types_path, class: "btn btn-warning text-center" %>
</div>

app/views/bill_types/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_bill_type_path(@bill_type) %> |
<%= link_to 'Back', bill_types_path %>