config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }, path: '/', path_names: {
      sign_in: 'login', sign_out: 'logout',
      password: 'secret', confirmation: 'verification',
      registration: 'register', edit: 'edit/profile'
  }
  authenticate :user do
    resources :bills do
      resources :bill_apportionments
    end  
    resources :bill_types do
      resources :bill_splitings
    end
    resources :houses, only: [:new, :create]
  end

  authenticated :user do
    root 'bill_types#index', as: :authenticated_root
  end
  root to: "home#index"
  #get 'bill_types/:id/split', action: :split, controller: 'bill_types', as: :bill_types_split
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bill_apportionment.rb
class BillApportionment < ApplicationRecord
  belongs_to :bill
  belongs_to :dweller
end

app/controllers/bill_apportionments_controller.rb
class BillApportionmentsController < ApplicationController
  before_action :set_bill_apportionments
  before_action :set_bill_apportionment, only: [:show, :edit, :update, :destroy]
  before_action :require_living

  # GET bills/1/bill_apportionments
  def index
    @bill_apportionments = @bill.bill_apportionments
  end

  # GET bills/1/bill_apportionments/1
  def show
  end

  # GET bills/1/bill_apportionments/new
  def new
    @dwellers = Dweller.where("house_id = ?", current_user.dweller.house.id)
    
    @bill_apportionment = @bill.bill_apportionments.build
  end

  # GET bills/1/bill_apportionments/1/edit
  def edit
  end

  # POST bills/1/bill_apportionments
  def create
    @bill_apportionment = BillApportionment::Create.new(@bill, bill_apportionment_params).call()
    redirect_to bill_bill_apportionments_path, notice: 'Bill apportionment was successfully created.'
    rescue => e
      flash.now[:error] = e.message
      @bill_apportionment = @bill.bill_apportionments.build(bill_apportionment_params)
      #TODO: just dwellers from the right house
      @dwellers = Dweller.all
      render :new
  end

  # PUT bills/1/bill_apportionments/1
  def update
    if @bill_apportionment.update_attributes(bill_apportionment_params)
      redirect_to([@bill_apportionment.bill, @bill_apportionment], notice: 'Bill apportionment was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE bills/1/bill_apportionments/1
  def destroy
    @bill_apportionment.destroy

    redirect_to bill_bill_apportionments_url(@bill)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill_apportionments
      @bill = Bill.find(params[:bill_id])
    end

    def set_bill_apportionment
      @bill_apportionment = @bill.bill_apportionments.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def bill_apportionment_params
      params.require(:bill_apportionment).permit(:value, :dweller_id)
    end
end

app/helpers/bill_apportionments_helper.rb
module BillApportionmentsHelper
end

app/views/bill_apportionments/_form.html.erb
<%= form_for([@bill_apportionment.bill, @bill_apportionment]) do |f| %>
  <% if @bill_apportionment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill_apportionment.errors.count, "error") %> prohibited this bill_apportionment from being saved:</h2>

      <ul>
      <% @bill_apportionment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :dweller %><br />
    <%= f.collection_select :dweller_id, @dwellers, :id, :name %>
  </div>
  <div class="actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/bill_apportionments/edit.html.erb
<h1>Editing bill_apportionment</h1>

<%= render 'form' %>

<%= link_to 'Show', [@bill_apportionment.bill, @bill_apportionment] %> |
<%= link_to 'Back', bill_bill_apportionments_path(@bill_apportionment.bill) %>

app/views/bill_apportionments/index.html.erb
<h1>Rateio da conta</h1>

<table>
  <tr>
    <th>Valor</th>
    <th>Morador</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bill_apportionments.each do |bill_apportionment| %>
  <tr>
    <td><%= bill_apportionment.value %></td>
    <td><%= bill_apportionment.dweller.name %></td>
    <td><%= link_to 'Abrir', [bill_apportionment.bill, bill_apportionment], class: "btn btn-primary float-right" %></td>
    <td><%= link_to 'Editar', edit_bill_bill_apportionment_path(bill_apportionment.bill, bill_apportionment), class: "btn btn-primary float-right" %></td>
    <td><%= link_to 'Apagar', [bill_apportionment.bill, bill_apportionment], :confirm => 'Are you sure?', :method => :delete, class: "btn btn-danger float-right" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo rateio', new_bill_bill_apportionment_path(params[:bill_id]), class: "btn btn-primary" %>
<div class="col-md-11 text-center">
  <%= link_to 'Voltar', bills_path, class: "btn btn-warning text-center" %>
</div>

app/views/bill_apportionments/new.html.erb
<h1>New bill_apportionment</h1>

<%= render 'form' %>

<div class="col-md-11 text-center">
  <%= link_to 'Back', bill_bill_apportionments_path(@bill_apportionment.bill), class: "btn btn-warning text-center" %>
</div>

app/views/bill_apportionments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Value:</b>
  <%= @bill_apportionment.value %>
</p>

<p>
  <b>Dweller:</b>
  <%= @bill_apportionment.dweller.name %>
</p>


<%= link_to 'Edit', edit_bill_bill_apportionment_path(@bill_apportionment.bill, @bill_apportionment) %> |
<%= link_to 'Back', bill_bill_apportionments_path(@bill_apportionment.bill) %>